# -*- coding: utf-8 -*-
"""RQ1_MLP_alpha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hv8_KirUQ--0BByh0S20wbATOB-x-how
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    balanced_accuracy_score,
)
from sklearn.neural_network import MLPClassifier
from sklearn.utils.class_weight import compute_sample_weight

"""# Mount on GoogleDrive"""

# from google.colab import drive
# drive.mount('/content/drive')

# """# Import Data"""

# df_rq1 = pd.read_csv("/content/drive/My Drive/COMP90049/processed/df_rq1_baseline.csv")
# print(df_rq1.shape)

# # Check target has no missing values
# assert df_rq1["target_fmd"].isnull().sum() == 0, "target_fmd has missing values"

# ── 1. Load data ──────────────────────────────────────────────────────────────
df_rq1 = pd.read_csv("df_rq1_baseline.csv")
print("Dataset shape:", df_rq1.shape)

assert df_rq1["target_fmd"].isnull().sum() == 0, "target_fmd has missing values!"


"""# Split Features and Targets"""

X = df_rq1.drop(columns=["target_fmd"])
y = df_rq1["target_fmd"]

print("y distribution:")
print(y.value_counts(normalize=True))

"""# Split train, validation and test data"""

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.4,
    random_state=42,
    stratify=y,
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp,
)

print(f"\nTrain      : {X_train.shape[0]:>6} rows ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"Validation : {X_val.shape[0]:>6} rows ({X_val.shape[0]/len(X)*100:.0f}%)")
print(f"Test       : {X_test.shape[0]:>6} rows ({X_test.shape[0]/len(X)*100:.0f}%)")

"""# Define feature groups"""

numeric_features = [
    "CHILDREN",
    "SLEPTIM1",
    "alcohol_days_30",
    "BMI",
    "chronic_count",
]

income_feature = ["INCOME3"]

categorical_features = [
    col for col in X.columns if col not in numeric_features + income_feature
]

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler",  StandardScaler()),
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot",  OneHotEncoder(handle_unknown="ignore")),
])

income_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value=-1)),
    ("onehot",  OneHotEncoder(handle_unknown="ignore")),
])

"""# Preprocessing pipeline"""

preprocessor = ColumnTransformer(transformers=[
    ("num",    numeric_transformer,     numeric_features),
    ("cat",    categorical_transformer, categorical_features),
    ("income", income_transformer,      income_feature),
])

# Fit preprocessor once — avoids re-fitting it 15 times inside the search loop
X_train_t = preprocessor.fit_transform(X_train, y_train)
X_val_t   = preprocessor.transform(X_val)
X_test_t  = preprocessor.transform(X_test)

# Class weights to counter the 84/16 imbalance (MLPClassifier has no class_weight param)
sample_weight_train = compute_sample_weight("balanced", y_train)

"""# Hyperparameter Tuning and Model Training


"""

best_hidden_layers = None
best_lr = None
best_alpha = None
best_val_score = -1

hidden_layer_candidates = [
    (64,),
    (128,),
    (64, 32),
    (128, 64),
    (128, 64, 32),
]

lr_candidates    = [0.001, 0.01, 0.0001]
alpha_candidates = [0.0001, 0.001, 0.01]   # L2 regularization strength

for hidden_layers in hidden_layer_candidates:
    for lr in lr_candidates:
        for alpha in alpha_candidates:
            clf = MLPClassifier(
                hidden_layer_sizes=hidden_layers,
                activation="relu",
                learning_rate_init=lr,
                alpha=alpha,
                max_iter=500,
                early_stopping=True,
                n_iter_no_change=30,
                validation_fraction=0.1,
                random_state=42,
            )
            clf.fit(X_train_t, y_train, sample_weight=sample_weight_train)
            val_score = balanced_accuracy_score(y_val, clf.predict(X_val_t))
            print(f"  hidden={str(hidden_layers):<15} lr={lr} alpha={alpha} → val balanced accuracy={val_score:.4f} (iters={clf.n_iter_})")

            if val_score > best_val_score:
                best_val_score = val_score
                best_hidden_layers = hidden_layers
                best_lr = lr
                best_alpha = alpha

print(f"\nBest: hidden={best_hidden_layers}, lr={best_lr}, alpha={best_alpha}  (val balanced_accuracy={best_val_score:.4f})")

"""# MLP classifier"""

final_clf = MLPClassifier(
    hidden_layer_sizes=best_hidden_layers,
    activation="relu",
    learning_rate_init=best_lr,
    alpha=best_alpha,
    max_iter=500,
    early_stopping=True,
    n_iter_no_change=30,
    validation_fraction=0.1,
    random_state=42,
)
final_clf.fit(X_train_t, y_train, sample_weight=sample_weight_train)

"""# Test Evaluation"""

print("\n── Final evaluation on TEST set ──")
y_pred = final_clf.predict(X_test_t)
y_prob = final_clf.predict_proba(X_test_t)[:, 1]

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print(f"\nBalanced Accuracy : {balanced_accuracy_score(y_test, y_pred):.4f}")
print(f"ROC AUC Score     : {roc_auc_score(y_test, y_prob):.4f}")