# -*- coding: utf-8 -*-
"""RQ1_pipeline_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xm485uyfYjb6eJdTv3s_lpFhsSj0aq7S
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, balanced_accuracy_score

"""# Mount on GoogleDrive"""

#from google.colab import drive
#drive.mount('/content/drive')

"""# Read RQ1 Dataset"""

import pandas as pd
#SAVE_DIR = "/content/drive/MyDrive/COMP90049/processed"

df_rq1 = pd.read_csv("df_rq1_baseline.csv")

print(df_rq1.shape)
df_rq1.head()

"""# Split Features and Targets"""

X = df_rq1.drop(columns=["target_fmd"])
y = df_rq1["target_fmd"]

print("X shape:", X.shape)
print("y shape:", y.shape)
print("y distribution:")
print(y.value_counts(normalize=True))

"""# Division of Training and Test sets"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y)

print("Train:", X_train.shape, y_train.shape)
print("Test:", X_test.shape, y_test.shape)

"""# Define Numeric / Categorical Features"""

numeric_features = [
    "CHILDREN",
    "SLEPTIM1",
    "alcohol_days_30",
    "BMI",
    "chronic_count"
]

income_feature = ["INCOME3"]

categorical_features = [
    col for col in X.columns if col not in numeric_features + income_feature
]

print("Numeric features:", numeric_features)
print("Income feature:", income_feature)
print("Categorical features:", categorical_features)

"""| Category          | Method                 |
| ----------- | ------------------ |
| numeric     | Medium + standardlization        |
| categorical | most frequent + one-hot     |
| INCOME3     | Missing as a separate category + one-hot |

Preprocessing Pipeline Template
"""

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

income_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value=-1)),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
        ('income', income_transformer, income_feature)
    ])

"""# Classifier (Run models in this part)"""

from sklearn.tree import DecisionTreeClassifier

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(
        criterion="gini",
        max_depth=8,
        min_samples_split=50,
        min_samples_leaf=20,
        class_weight="balanced",
        random_state=42
    ))
])

"""# Train and Evaluation"""

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

if hasattr(model, "predict_proba"):
    y_prob = model.predict_proba(X_test)[:, 1]
else:
  y_prob = None

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("Balanced Accuracy:")
print(balanced_accuracy_score(y_test, y_pred))

if y_prob is not None:
    print("ROC AUC Score:")
    print(roc_auc_score(y_test, y_prob))